package optimizer

import "time"

// Suggestion represents an optimization recommendation generated by analyzing the token ledger.
type Suggestion struct {
	ID               int        `json:"id"`
	Type             string     `json:"type"`              // e.g., "model_switch", "prompt_optimization", "retry_strategy"
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	EstimatedSavings float64    `json:"estimated_savings"`
	SavingsUnit      string     `json:"savings_unit"`      // "USD" or "tokens"
	TargetFlowID     string     `json:"target_flow_id"`
	TargetCommandID  int        `json:"target_command_id"`
	ApplyAction      string     `json:"apply_action"`      // JSON payload for applying this suggestion
	Status           string     `json:"status"`            // "pending" or "applied"
	AppliedAt        *time.Time `json:"applied_at,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
}

// ApplyAction represents the parsed action to be applied
type ApplyAction struct {
	Action    string `json:"action"`              // model_switch, prompt_optimization, retry_strategy
	FlowID    string `json:"flow_id,omitempty"`
	FromModel string `json:"from_model,omitempty"`
	ToModel   string `json:"to_model,omitempty"`
	AgentRole string `json:"agent_role,omitempty"`
}

// ApplyResult contains the result of applying an optimization
type ApplyResult struct {
	Success     bool   `json:"success"`
	Message     string `json:"message"`
	ChangesApplied string `json:"changes_applied,omitempty"`
}
