package optimizer

// Suggestion represents an optimization recommendation generated by analyzing the token ledger.
// Educational Comment: This struct defines the core data structure for optimization suggestions.
// The EstimatedSavings field helps users prioritize which optimizations to apply first.
// The ApplyAction field contains a JSON payload that can be used to automate applying the suggestion.
type Suggestion struct {
	ID               int     `json:"id"`                // Unique identifier for this suggestion
	Type             string  `json:"type"`              // e.g., "model_switch", "prompt_optimization", "retry_strategy"
	Title            string  `json:"title"`             // Short, user-friendly title
	Description      string  `json:"description"`       // Detailed explanation of the optimization
	EstimatedSavings float64 `json:"estimated_savings"` // Estimated savings in USD or tokens
	SavingsUnit      string  `json:"savings_unit"`      // "USD" or "tokens"
	TargetFlowID     string  `json:"target_flow_id"`    // The flow this suggestion applies to
	TargetCommandID  int     `json:"target_command_id"` // The command this suggestion applies to (if applicable)
	ApplyAction      string  `json:"apply_action"`      // JSON payload for applying this suggestion
}
