// Package data provides data models for the Forge Orchestrator.
// These models represent the structures stored in the database.
package data

import "time"

// TokenLedgerEntry represents a single record in the token_ledger table.
// Each entry tracks one API call made to an external LLM provider.
// Think of it as a receipt for every AI interaction.
type TokenLedgerEntry struct {
	// ID is the unique identifier for this entry (auto-generated by the database).
	ID int64

	// Timestamp is when this API call was made.
	Timestamp time.Time

	// FlowID identifies which workflow this call belongs to.
	// This helps group related API calls together.
	FlowID string

	// ModelUsed is the specific model that was called (e.g., "claude-3-5-sonnet", "gpt-4o").
	ModelUsed string

	// AgentRole identifies which type of agent made this call (e.g., "Architect", "Coder").
	AgentRole string

	// PromptHash is a hash of the prompt sent to the LLM.
	// We hash it to avoid storing sensitive code, but allow comparison.
	PromptHash string

	// InputTokens is the number of tokens in the prompt sent to the LLM.
	InputTokens int

	// OutputTokens is the number of tokens in the response from the LLM.
	OutputTokens int

	// TotalCostUSD is the estimated cost of this API call in US dollars.
	TotalCostUSD float64

	// LatencyMs is how long the API call took in milliseconds.
	LatencyMs int

	// Status indicates the result of the API call: "SUCCESS", "FAILED", or "TIMEOUT".
	Status string

	// ErrorMessage contains details if the call failed (empty on success).
	ErrorMessage string
}
