// Package data provides data models for the Forge Orchestrator.
// These models represent the structures stored in the database.
package data

import "time"

// TokenLedgerEntry represents a single record in the token_ledger table.
// Each entry tracks one API call made to an external LLM provider.
// This is the canonical model used throughout the application.
type TokenLedgerEntry struct {
	// ID is the unique identifier for this entry (auto-generated by the database).
	ID int64 `json:"id"`

	// Timestamp is when this API call was made.
	Timestamp time.Time `json:"timestamp"`

	// FlowID identifies which workflow this call belongs to.
	FlowID string `json:"flow_id"`

	// ModelUsed is the specific model that was called (e.g., "claude-3-5-sonnet", "gpt-4o").
	ModelUsed string `json:"model_used"`

	// AgentRole identifies which type of agent made this call (e.g., "Architect", "Coder").
	AgentRole string `json:"agent_role"`

	// PromptHash is a hash of the prompt sent to the LLM.
	PromptHash string `json:"prompt_hash"`

	// InputTokens is the number of tokens in the prompt sent to the LLM.
	InputTokens int `json:"input_tokens"`

	// OutputTokens is the number of tokens in the response from the LLM.
	OutputTokens int `json:"output_tokens"`

	// TotalCostUSD is the estimated cost of this API call in US dollars.
	TotalCostUSD float64 `json:"total_cost_usd"`

	// LatencyMs is how long the API call took in milliseconds.
	LatencyMs int `json:"latency_ms"`

	// Status indicates the result of the API call: "SUCCESS", "FAILED", or "TIMEOUT".
	Status string `json:"status"`

	// ErrorMessage contains details if the call failed (empty on success).
	ErrorMessage string `json:"error_message,omitempty"`
}
